language: node_js
before_install:
- npm run start
install:
- npm install
before_script:
- npm install -g codeclimate-test-reporter
- npm install -g coveralls
script: 'true'0
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
- npm run coveralls
- codeclimate-test-reporter < coverage/lcov.info
- coveralls < coverage/lcov.info
after_failure:

before_deploy: 'true'
deploy: 'true'
after_deploy: 'true'
branches:
  only:
  - gh-pages
  - /.*/
matrix:
  exclude:
- env:DB=mongodb
- env:DB=postgreSql
