const user=[
    {
    id:1,
    fullName:"Ejiro Rapheal",
    userName:"Rafjiro",
    email:'ejiro.r@gmail.com',
    password:'Th(15)^2ejir',
    sex:'M',
    title:"Beginner backend developer",
    stack:["python","javascript"],
    bio:'Graduate of computer engineering, loves playing chess, sleeps on code',
    quote:'still on the coding diet',
    },
    {
    id:2,
    fullName:"Amanda Amandianeze",
    userName:"itzAmanda",
    email:'amanda.a@gmail.com',
    password:'AmandaSquared',
    sex:'F',
    title:"front-end developer, UI/UX",
    stack:["javascript","React","Jquery"],
    bio:'Coded biochemist,likes to party,devout christian',
    quote:'No one knew she fell in love with a programmer because everything was so coded',
    },
    {
    id:3,
    fullName:"Lipieng Atchu",
    userName:"AtchuYoung",
    email:'lipieng.a@gmail.com',
    password:'Yasmin12A',
    sex:'M',
    title:"full stack javascript developer",
    stack:["Javascript","Node",'Express','React','Electron'],
    bio:'',
    quote:'',
    },
    {
    id:4,
    fullName:"Ogbonna Basil",
    userName:"cea",
    email:'ogbonna.b@gmail.com',
    sex:"M",
    password:'ThisNaDemo',
    title:"Beginner Full stack developer",
    stack:["Python","Javascript","Node","Java","Express","Jupyter"],
    bio:'{software developer}; data.science.enthusiast',
    quote:'Great Quotes dont make a man, living by them do',
    },
    {
    id:5,
    fullName:"Treasure Tshu",
    userName:"TT",
    email:'treasure.t@gmail.co.uk',
    sex:"F",
    password:'TTFro1And3la',
    title:"Solution Architect",
    stack:["javascript","Ruby"],
    bio:'Ambivert, Eclectic, loves to look fro',
    quote:"Yinmu,dont think i have your time, am busy designing the world's solution",
    }
]
export default user;